name: demo
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  clone:
    runs-on: windows-latest
    
    permissions: read-all

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Git clone
      run: |
        mkdir .github/test
        mkdir .github/test/client
        git clone https://github.com/react-refactor-tool-on-vscode/RRTV-client.git .github/test/client
        mkdir .github/test/server
        git clone https://github.com/react-refactor-tool-on-vscode/RRTV-server.git .github/test/server

    - name: Configure version
      run: |
        cd .github/test
        cp ../../package.json package.json
        cp ../../LICENSE.md LICENSE.md
        cd ../..
        node update-package-version.js
        cd .github/test
        pwd
        ls

    - name: Package all
      run: |
        npm i @vscode/vsce -g
        vsce package
      
    - name: Move VSIX file
      run: |
        mkdir downloads
        mv react-refactor-tool-on-vscode-0.0.1.vsix downloads/
        ls downloads
      
    - name: Get package version
      id: get_version
      run: |
        echo "::set-output name=version::$(node -p "require('./package.json').version")"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: v0.0.1
        release_name: Release v0.0.1
        draft: true
        prerelease: false
    
    - name: Get Release Upload URL
      uses: actions/github-script@v4
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        script: |
          const response = await github.repos.getReleaseByTag({
            owner: '${{ github.repository_owner }}',
            repo: '${{ github.event.repository.name }}',
            tag: 'v${{ steps.get_version.outputs.version }}',
          });
          console.log(response.data.upload_url);

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ steps.Get_Release_Upload_URL.outputs.upload_url }}
        asset_path: ./dowmloads/react-refactor-tool-on-vscode-0.0.1.vsix
        asset_name: react-refactor-tool-on-vscode-0.0.1.vsix
        asset_content_type: application/octet-stream