name: demo
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  clone:
    runs-on: windows-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Git clone
      run: |
        mkdir .github/test
        git clone https://github.com/react-refactor-tool-on-vscode/RRTV-client.git .github/test
        git clone https://github.com/react-refactor-tool-on-vscode/RRTV-server.git .github/test
        mkdir .github/package
        git clone https://github.com/Crush-0/workflows.git .github/package

    - name: Configure version
      run: |
        cd .github/test
        cp ../package/workflows/package.json package.json
        cp ../package/workflows/package.json LICENSE.md
        cd ../package/workflows
        node update-package-version.js
        cd ../../test

    - name: Package all
      run: 
        vsce package
      

    - uses: GoogleCloudPlatform/release-please-action@v3
      id: release
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        release-type: node
        package-name: standard-version
        changelog-types: '[{"type": "types", "section":"Types", "hidden": false},{"type": "revert", "section":"Reverts", "hidden": false},{"type": "feat", "section": "Features", "hidden": false},{"type": "fix", "section": "Bug Fixes", "hidden": false},{"type": "improvement", "section": "Feature Improvements", "hidden": false},{"type": "docs", "section":"Docs", "hidden": false},{"type": "style", "section":"Styling", "hidden": false},{"type": "refactor", "section":"Code Refactoring", "hidden": false},{"type": "perf", "section":"Performance Improvements", "hidden": false},{"type": "test", "section":"Tests", "hidden": false},{"type": "build", "section":"Build System", "hidden": false},{"type": "ci", "section":"CI", "hidden":false}]'