name: github-actions-demo2
on:
  push:
    branches:
      ["main"]
jobs:
  clone:
    runs-on: [self-hosted,windows-lastest]

    steps:
    - name: Git clone
      run: git clone https://github.com/Crush-0/workflows C:\Users\ChengYao\Desktop\train\github-action\test